markers = [
["a", "striking", "difference"],
["accepting", "that"],
["admittedly"],
["after", "all"],
["after", "this"],
["against"],
["allowing", "that"],
["although"],
["also"],
["as", "well", "as"],
["and", "yet"],
["another", "distinction"],
["but"],
["by", "contrast"],
["because"],
["conversely"],
["contrasting", "with"],
["corresponding", "with"],
["correspondingly"],
["certainly"],
["despite"],
["doubtless"],
["even", "so"],
["equally"],
["for", "all", "that"],
["fortunately"],
["furthermore"],
["further", "more"],
["first", "and", "foremost"],
["finally"],
["firstly"],
["granted", "that"],
["however"],
["indeed"],
["if"],
["in", "another", "way"],
["in", "the", "first", "place"],
["in", "contrast"],
["in", "addition"],
["in", "one", "way"],
["in", "the", "same", "way"],
["in", "opposition", "to"],
["in", "opposite", "to"],
["in", "spite", "of"],
["instead"],
["it", "is", "true", "that"],
["it","'","s" ,"true", "that"],
["it", "may", "well", "be"],
["in", "comparison"],
["in", "conclusion"],
["likewise"],
["naturally"],
["nevertheless"],
["no", "doubt"],
["nonetheless"],
["moreover"],
["of", "course"],
["on", "one", "hand"],
["on", "the", "other", "hand"],
["on", "the", "contrary"],
["opposite"],
["otherwise"],
["still"],
["similarly"],
["secondly"],
["subsequently"],
["primarily"],
["though"],
["lastly"],
["to", "differ", "from"],
["to", "oppose"],
["to", "begin", "with"],
["the", "opposite"],
["this", "can", "be"],
["this", "can", "also", "be"],
["this", "can", "not", "be"],
["this", "can","'","t" ,"be"],
["therefore"],
["thus"],
["thirdly"],
["unexpectedly"],
["unfortunately"],
["unlike"],
["until"],
["versus"],
["without"],
["while", "it","is" ,"true"],
["while", "it", "'","s" ,"true"],
["whereas"],
["what", "is", "more"],
["what","'" ,"s","more"],
["we", "can", "conclude"],
["yet"]
]
